import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Header
    'header.config': 'Configuración',
    'header.guide': 'Guía Técnica',
    'header.about': 'Acerca de',
    'header.menu': 'Menú',
    'header.theme.light': 'Claro',
    'header.theme.dark': 'Oscuro',
    
    // Home
    'home.footer': 'Haz clic en cualquier máquina virtual para ver más detalles',
    
    // Configuration
    'config.title': 'Guía Técnica y Troubleshooting',
    'config.subtitle': 'Documentación completa de instalación, configuración y resolución de problemas',
    'config.toc': 'Índice de Contenidos',
    'config.back': 'Volver al diagrama',
    'config.copy': 'Copiar',
    'config.copied': 'Copiado',
    
    // About
    'about.title': 'Acerca de la Arquitectura',
    'about.subtitle': 'Información detallada sobre el sistema Proxmox y sus máquinas virtuales',
    'about.overview.title': 'Visión General del Sistema',
    'about.overview.intro': 'Este sistema está construido sobre',
    'about.overview.proxmox': 'Proxmox VE',
    'about.overview.description': 'un hipervisor de código abierto basado en KVM que permite ejecutar múltiples máquinas virtuales en un único servidor físico.',
    'about.overview.features': 'La arquitectura está diseñada para separar roles y responsabilidades, permitiendo:',
    'about.overview.storage': 'Almacenamiento centralizado y compartido (NFS)',
    'about.overview.production': 'Servicios de producción aislados y críticos',
    'about.overview.gpu': 'Aceleración GPU para cargas de trabajo especializadas',
    'about.overview.cicd': 'Entorno de desarrollo y CI/CD separado de producción',
    'about.hardware.title': 'Especificaciones del Hardware Físico',
    'about.hardware.cpu': 'CPU',
    'about.hardware.cpuValue': 'núcleos físicos',
    'about.hardware.ram': 'RAM',
    'about.hardware.ramValue': 'GB de memoria física',
    'about.hardware.gpu': 'GPU',
    'about.hardware.gpuValue': 'NVIDIA GTX 1060 6GB (passthrough a VM103)',
    'about.hardware.storage': 'Almacenamiento',
    'about.hardware.storageValue': 'HDD array + SSD para discos del sistema',
    'about.resources.title': 'Asignación de Recursos',
    'about.resources.description': 'La estrategia de asignación de recursos utiliza overcommit controlado:',
    'about.resources.cpu': 'CPU Overcommit',
    'about.resources.cpuDesc': 'Se asignan',
    'about.resources.ram': 'RAM Overcommit',
    'about.resources.ramDesc': 'Se asignan',
    'about.resources.on': 'en',
    'about.resources.physical': 'físicos',
    'about.resources.ratio': 'ratio',
    'about.resources.overcommit': 'overcommit',
    'about.concepts.title': 'Conceptos Clave',
    'about.concepts.nfs': 'NFS (Network File System)',
    'about.concepts.nfsDesc': 'Protocolo que permite compartir almacenamiento entre máquinas. TrueNAS (VM101) actúa como servidor NFS, proporcionando almacenamiento compartido a todas las demás VMs.',
    'about.concepts.docker': 'Docker & Containers',
    'about.concepts.dockerDesc': 'Tecnología de containerización que permite empaquetar aplicaciones con sus dependencias. Utilizado en VM102, VM103 y VM104 para ejecutar servicios aislados.',
    'about.concepts.jenkins': 'Jenkins CI/CD',
    'about.concepts.jenkinsDesc': 'Sistema de automatización que orquesta pipelines de construcción, prueba y despliegue. Jenkins Master (VM102) coordina con Jenkins Agent (VM104).',
    'about.concepts.passthrough': 'GPU Passthrough',
    'about.concepts.passthroughDesc': 'Técnica que permite que una VM acceda directamente a un dispositivo GPU físico. Requiere configuración especial (q35 chipset, OVMF BIOS, IOMMU habilitado).',
    'about.practices.title': 'Mejores Prácticas',
    'about.practices.monitor': 'Monitorear el uso de memoria con',
    'about.practices.monitorDesc': 'para detectar presión de memoria',
    'about.practices.backup': 'Realizar backups regulares de VMs críticas (VM101, VM102, VM103)',
    'about.practices.snapshots': 'Usar snapshots de ZFS en TrueNAS para protección de datos',
    'about.practices.separate': 'Mantener separados los entornos de desarrollo (VM104) y producción (VM102)',
    'about.explore.title': 'Explorar la Arquitectura',
    'about.explore.description': 'Haz clic en cualquier máquina virtual en el diagrama para ver detalles específicos de su configuración, servicios, y guía de troubleshooting.',
    'about.explore.button': 'Ir al Diagrama Interactivo',
    'about.back': 'Volver al diagrama',
    
    // Configuration Guide
    'configGuide.resources.title': 'Resumen de Recursos',
    'configGuide.resources.cpu': 'CPU',
    'configGuide.resources.ram': 'RAM',
    'configGuide.resources.physical': 'Físico',
    'configGuide.resources.assigned': 'Asignado',
    'configGuide.resources.ratio': 'Ratio',
    'configGuide.resources.cores': 'núcleos',
    'configGuide.resources.overcommit': 'Overcommit',
    'configGuide.vms.title': 'Máquinas Virtuales',
    
    // Technical Guide - Sections
    'techGuide.physical.title': 'Infraestructura Física',
    'techGuide.physical.description': 'Especificaciones del hardware físico del servidor Proxmox',
    'techGuide.physical.content': 'El servidor Proxmox cuenta con 4 núcleos físicos, 32GB de RAM, una GPU NVIDIA GTX 1060 de 6GB con passthrough, y almacenamiento HDD con SSD para discos del sistema.',
    'techGuide.physical.cpuRam.title': 'CPU y RAM',
    'techGuide.physical.cpuRam.content': 'El servidor dispone de 4 núcleos físicos y 32GB de memoria RAM física.',
    'techGuide.physical.gpuStorage.title': 'GPU y Almacenamiento',
    'techGuide.physical.gpuStorage.content': 'NVIDIA GTX 1060 6GB disponible para passthrough a VM103. Almacenamiento con HDD array (passthrough a TrueNAS) y SSD para discos del sistema de las VMs.',
    'techGuide.physical.resourceAllocation.title': 'Estrategia de Asignación de Recursos',
    'techGuide.physical.resourceAllocation.content': 'Se utiliza overcommit controlado: 8 vCPU asignados en 4 núcleos (2:1 ratio, normal en virtualización) y 38GB RAM asignados en 32GB físicos (6GB overcommit, aceptable porque TrueNAS y VM103 raramente usan el máximo).',
    
    'techGuide.vms.title': 'Configuración de Máquinas Virtuales',
    'techGuide.vms.description': 'Detalles de configuración de cada máquina virtual',
    'techGuide.vms.content': 'Cuatro máquinas virtuales principales: TrueNAS (almacenamiento), DockerHost (producción), GPUProduction (GPU), y StagingAgent (desarrollo/CI/CD).',
    'techGuide.vms.vm101.title': 'VM101 - TrueNAS (Storage Server)',
    'techGuide.vms.vm101.content': 'Servidor de almacenamiento NFS que proporciona exportaciones para todas las VMs. Configuración: 2 Cores, 16GB RAM, UEFI BIOS, Passthrough HDD, QEMU Guest Agent habilitado.',
    'techGuide.vms.vm102.title': 'VM102 - DockerHost (Production Server)',
    'techGuide.vms.vm102.content': 'Entorno de producción principal con Docker, Nginx Reverse Proxy y Jenkins Master. Criticidad: ALTA - sin downtime permitido.',
    'techGuide.vms.vm103.title': 'VM103 - GPUProduction (GPU Production Server)',
    'techGuide.vms.vm103.content': 'Servicios acelerados por GPU para media y AI workloads. CRÍTICO - sin downtime permitido. Requiere configuración especial para GPU passthrough.',
    'techGuide.vms.vm104.title': 'VM104 - StagingAgent (Development & CI/CD Agent)',
    'techGuide.vms.vm104.content': 'Agente de Jenkins y entorno de desarrollo/testing. Criticidad: MEDIA - puede ser reiniciado sin afectar producción.',
    
    'techGuide.installation.title': 'Instalación y Configuración',
    'techGuide.installation.description': 'Guías paso a paso para instalar y configurar cada componente',
    'techGuide.installation.content': 'Procedimientos estándar para configurar Ubuntu VMs, Docker, NFS, GPU y Jenkins.',
    'techGuide.installation.ubuntu.title': 'Configuración Estándar de Ubuntu VM',
    'techGuide.installation.ubuntu.content': 'Pasos para configurar una nueva VM Ubuntu con Docker, NFS y herramientas útiles.',
    'techGuide.installation.gpu.title': 'Configuración de GPU (VM103)',
    'techGuide.installation.gpu.content': 'Pasos adicionales para configurar GPU en VM103 después de la configuración base.',
    'techGuide.installation.jenkinsMaster.title': 'Configuración de Jenkins Master (VM102)',
    'techGuide.installation.jenkinsMaster.content': 'Instalación de Jenkins Master como contenedor Docker en VM102.',
    'techGuide.installation.jenkinsAgent.title': 'Configuración de Jenkins Agent (VM104)',
    'techGuide.installation.jenkinsAgent.content': 'Configuración de VM104 como agente de Jenkins.',
    
    'techGuide.backup.title': 'Estrategia de Backup',
    'techGuide.backup.description': 'Procedimientos de backup para VMs y datos',
    'techGuide.backup.content': 'Snapshots de Proxmox, backups de Docker volumes y snapshots de ZFS en TrueNAS.',
    'techGuide.backup.proxmox.title': 'Backups de Proxmox VMs',
    'techGuide.backup.proxmox.content': 'Snapshots y backups de máquinas virtuales críticas.',
    'techGuide.backup.docker.title': 'Backups de Docker Volumes',
    'techGuide.backup.docker.content': 'Script automatizado para backup de volúmenes Docker.',
    'techGuide.backup.zfs.title': 'ZFS Snapshots (TrueNAS)',
    'techGuide.backup.zfs.content': 'Configuración de snapshots automáticos en TrueNAS.',
    
    'techGuide.monitoring.title': 'Monitoreo y Mantenimiento',
    'techGuide.monitoring.description': 'Comandos y procedimientos para monitorear el sistema',
    'techGuide.monitoring.content': 'Herramientas y comandos para monitorear Proxmox, Docker, red y GPU.',
    'techGuide.monitoring.proxmox.title': 'Monitoreo de Proxmox Host',
    'techGuide.monitoring.proxmox.content': 'Comandos para monitorear el estado del hipervisor y VMs.',
    'techGuide.monitoring.docker.title': 'Monitoreo de Docker',
    'techGuide.monitoring.docker.content': 'Comandos para monitorear contenedores y recursos Docker.',
    'techGuide.monitoring.gpu.title': 'Monitoreo de GPU (VM103)',
    'techGuide.monitoring.gpu.content': 'Comandos para monitorear el estado y uso de GPU.',
    'techGuide.monitoring.network.title': 'Diagnósticos de Red',
    'techGuide.monitoring.network.content': 'Comandos para diagnosticar problemas de conectividad.',
    
    'techGuide.troubleshooting.title': 'Guía de Troubleshooting',
    'techGuide.troubleshooting.description': 'Soluciones para problemas comunes',
    'techGuide.troubleshooting.content': 'Procedimientos para diagnosticar y resolver problemas frecuentes en el sistema.',
    'techGuide.troubleshooting.vmWontStart.title': 'VM No Inicia',
    'techGuide.troubleshooting.vmWontStart.content': 'Pasos para diagnosticar por qué una VM no puede iniciarse.',
    'techGuide.troubleshooting.nfsMountFails.title': 'Fallo de Montaje NFS',
    'techGuide.troubleshooting.nfsMountFails.content': 'Diagnóstico y solución de problemas de NFS.',
    'techGuide.troubleshooting.dockerWontStart.title': 'Contenedor Docker No Inicia',
    'techGuide.troubleshooting.dockerWontStart.content': 'Diagnóstico de problemas con contenedores Docker.',
    'techGuide.troubleshooting.gpuPassthrough.title': 'Problemas de GPU Passthrough (VM103)',
    'techGuide.troubleshooting.gpuPassthrough.content': 'Diagnóstico de problemas con el passthrough de GPU.',
    'techGuide.troubleshooting.jenkinsAgent.title': 'Problemas de Conexión de Jenkins Agent',
    'techGuide.troubleshooting.jenkinsAgent.content': 'Diagnóstico de problemas de conexión entre Jenkins Master y Agent.',
    'techGuide.troubleshooting.outOfMemory.title': 'Falta de Memoria (RAM Overcommit)',
    'techGuide.troubleshooting.outOfMemory.content': 'Diagnóstico y solución de problemas de presión de memoria.',
    'techGuide.troubleshooting.diskSpace.title': 'Problemas de Espacio en Disco',
    'techGuide.troubleshooting.diskSpace.content': 'Diagnóstico y liberación de espacio en disco.',
    'techGuide.troubleshooting.networkConnectivity.title': 'Problemas de Conectividad de Red',
    'techGuide.troubleshooting.networkConnectivity.content': 'Diagnóstico de problemas de red.',
    'techGuide.troubleshooting.slowPerformance.title': 'Rendimiento Lento',
    'techGuide.troubleshooting.slowPerformance.content': 'Diagnóstico de problemas de rendimiento.',
    'techGuide.troubleshooting.reverseProxy.title': 'Problemas con Reverse Proxy',
    'techGuide.troubleshooting.reverseProxy.content': 'Diagnóstico de problemas con Nginx reverse proxy.',
    
    'techGuide.security.title': 'Consideraciones de Seguridad',
    'techGuide.security.description': 'Configuración de seguridad y hardening',
    'techGuide.security.content': 'Mejores prácticas de seguridad para Proxmox, Docker, Jenkins y SSH.',
    'techGuide.security.firewall.title': 'Configuración de Firewall',
    'techGuide.security.firewall.content': 'Reglas de firewall para Proxmox y VMs.',
    'techGuide.security.jenkins.title': 'Seguridad de Jenkins',
    'techGuide.security.jenkins.content': 'Mejores prácticas de seguridad para Jenkins.',
    'techGuide.security.docker.title': 'Seguridad de Docker',
    'techGuide.security.docker.content': 'Mejores prácticas de seguridad para Docker.',
    'techGuide.security.ssh.title': 'Hardening de SSH',
    'techGuide.security.ssh.content': 'Configuración segura de SSH en todas las VMs.',
    
    // ArchitectureDiagram
    'diagram.clickDetails': 'Click para más detalles',
    'diagram.services': 'Servicios',
    'diagram.specialHardware': 'Hardware Especial',
    'diagram.cpu': 'CPU',
    'diagram.ram': 'RAM',
    'diagram.gb': 'GB',
    'diagram.nfsSharedStorage': 'Almacenamiento compartido NFS',
    'diagram.proxmoxHypervisor': 'Hipervisor Proxmox VE',
    'diagram.internetAccess': 'Acceso desde internet',
    'diagram.gpu': 'GPU',
    'diagram.passthroughToVm': 'Passthrough a VM',
    'diagram.storage': 'Almacenamiento',
    'diagram.passthroughToTruenas': 'Passthrough a TrueNAS',
    'diagram.externalClient': 'Cliente Externo\n(Internet)',
    'diagram.passthrough': 'Passthrough',
    'diagram.manages': 'Gestiona',
    'diagram.hddPassthrough': 'HDD Passthrough',
    'diagram.nfsServer': 'NFS Server',
    'diagram.nfsMount': 'NFS Mount',
    'diagram.gpuPassthrough': 'GPU Passthrough',
    'diagram.internet': 'Internet',
    'diagram.httpHttps': 'HTTP/HTTPS',
    'diagram.proxyTo': 'Proxy → Jellyfin/Ollama',
    'diagram.jenkinsMaster': 'Jenkins Master',
    'diagram.buildResults': 'Build Results',
    'diagram.data': 'Datos',
    'diagram.media': 'Media',
    'diagram.workspace': 'Workspace',
    'diagram.hddSsd': 'HDD + SSD',
    'diagram.controls': 'Controles',
    'diagram.showAllServices': 'Mostrar todos los servicios',
    'diagram.hideAllServices': 'Ocultar todos los servicios',
    'diagram.vmControl': 'Control de VMs',
    'diagram.showAll': 'Mostrar Todos',
    'diagram.hideAll': 'Ocultar Todos',
    'diagram.saveCheckpoint': 'Guardar Checkpoint',
    'diagram.legend': 'Leyenda',
    'diagram.provides': 'Proporciona',
    'diagram.showServices': 'Mostrar servicios',
    'diagram.hideServices': 'Ocultar servicios',
    'diagram.customConnection': 'Conexión personalizada',
    'diagram.instructions': 'Instrucciones',
    'diagram.clickEdge': 'Click en una conexión para seleccionarla',
    'diagram.pressDelete': 'Presiona Delete/Backspace para eliminar',
    'diagram.doubleClickEdit': 'Doble-click en una conexión para editarla o eliminarla',
    'diagram.editLabel': 'Editar Etiqueta de Conexión',
    'diagram.labelText': 'Texto de la etiqueta',
    'diagram.enterLabel': 'Escribe el nuevo nombre...',
    'diagram.resetConnections': 'Restablecer Conexiones',
    'diagram.resetDiagram': 'Restablecer Diagrama',
    'diagram.confirmReset': '¿Estás seguro de que deseas restablecer todas las conexiones a su estado por defecto? Se eliminarán todas las conexiones personalizadas y etiquetas modificadas.',
    
    // VM Detail
    'vm.back': 'Volver al diagrama',
    'vm.notFound': 'Máquina Virtual no encontrada',
    'vm.notFoundDesc': 'no existe en la arquitectura.',
    'vm.notFoundButton': 'Volver al diagrama',
    'vm.hardware': 'Configuración de Hardware',
    'vm.hardware.cpu': 'CPU',
    'vm.hardware.cores': 'Cores',
    'vm.hardware.ram': 'RAM',
    'vm.hardware.disk': 'Disco',
    'vm.hardware.bios': 'BIOS',
    'vm.hardware.machine': 'Tipo de Máquina',
    'vm.hardware.special': 'Hardware Especial',
    'vm.services': 'Servicios',
    'vm.servicesDesc': 'Aplicaciones disponibles para uso',
    'vm.software': 'Software y Tecnologías',
    'vm.softwareDesc': 'Stack tecnológico y herramientas del sistema',
    'vm.editConfig': 'Editar Configuración',
    'vm.addService': 'Agregar Aplicación',
    'vm.addSoftware': 'Agregar Tecnología',
    'vm.newServicePlaceholder': 'Nombre de la aplicación',
    'vm.newSoftwarePlaceholder': 'Nombre de la tecnología',
    'vm.nfs': 'Montes NFS',
    'vm.ports': 'Puertos',
    'vm.portsExposed': 'Puertos Expuestos',
    'vm.portsInternal': 'Puertos Internos',
    'vm.design': 'Motivo de las Elecciones de Diseño',
    'vm.troubleshooting': 'Guía de Troubleshooting',
    
    // NotFound
    'notFound.title': 'Página No Encontrada',
    'notFound.description': 'Lo sentimos, la página que buscas no existe.',
    'notFound.description2': 'Puede haber sido movida o eliminada.',
    'notFound.button': 'Ir al Inicio',
    
    // ErrorBoundary
    'error.title': 'Ha ocurrido un error inesperado.',
    'error.reload': 'Recargar Página',
    
    // Footer
    'footer.text': 'Architecture Dashboard',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.logout': 'Cerrar Sesión',
    'auth.username': 'Usuario',
    'auth.password': 'Contraseña',
    'auth.usernamePlaceholder': 'Ingresa tu usuario',
    'auth.passwordPlaceholder': 'Ingresa tu contraseña',
    'auth.loggingIn': 'Iniciando sesión...',
    'auth.loginSuccess': 'Sesión iniciada correctamente',
    'auth.loginError': 'Usuario o contraseña incorrectos',
    'auth.loginRequired': 'Debes iniciar sesión para realizar esta acción',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.add': 'Añadir',
    'common.remove': 'Eliminar',
    'common.reset': 'Restablecer',
    'common.confirm': 'Confirmar',
    
    // System Configuration
    'sysconfig.title': 'Configuración del Sistema',
    'sysconfig.subtitle': 'Configura tu infraestructura Proxmox y máquinas virtuales',
    'sysconfig.proxmox': 'Servidor Proxmox',
    'sysconfig.proxmox.name': 'Nombre',
    'sysconfig.proxmox.cpu': 'CPU (Cores)',
    'sysconfig.proxmox.ram': 'RAM (GB)',
    'sysconfig.proxmox.gpu': 'GPU',
    'sysconfig.proxmox.storage': 'Almacenamiento',
    'sysconfig.vms': 'Máquinas Virtuales',
    'sysconfig.vm.add': 'Añadir VM',
    'sysconfig.vm.name': 'Nombre',
    'sysconfig.vm.id': 'ID de VM',
    'sysconfig.vm.role': 'Rol',
    'sysconfig.vm.description': 'Descripción',
    'sysconfig.vm.criticality': 'Criticidad',
    'sysconfig.vm.cpu': 'CPU (Cores)',
    'sysconfig.vm.ram': 'RAM (GB)',
    'sysconfig.vm.disk': 'Disco (GB)',
    'sysconfig.vm.diskType': 'Tipo de Disco',
    'sysconfig.vm.bios': 'BIOS',
    'sysconfig.vm.machineType': 'Tipo de Máquina',
    'sysconfig.vm.color': 'Color',
    'sysconfig.vm.services': 'Servicios',
    'sysconfig.vm.software': 'Software y Tecnologías',
    'sysconfig.vm.specialHardware': 'Hardware Especial',
    'sysconfig.vm.nfsMounts': 'Montes NFS',
    'sysconfig.vm.ports': 'Puertos',
    'sysconfig.vm.portsExposed': 'Puertos Expuestos',
    'sysconfig.vm.portsInternal': 'Puertos Internos',
    'sysconfig.portPlaceholder': 'Ej: 80 (HTTP)',
    'sysconfig.vm.remove': 'Eliminar VM',
    'sysconfig.services.title': 'Servicios Globales',
    'sysconfig.services.add': 'Agregar Servicio',
    'sysconfig.services.name': 'Nombre',
    'sysconfig.services.imageUrl': 'URL de Imagen',
    'sysconfig.services.remove': 'Eliminar',
    'sysconfig.services.confirmRemove': '¿Estás seguro de que deseas eliminar este servicio? Se eliminará de todas las VMs que lo usen.',
    'sysconfig.vm.confirmRemove': '¿Estás seguro de que deseas eliminar esta VM?',
    'sysconfig.save': 'Guardar Configuración',
    'sysconfig.reset': 'Restablecer a Valores Por Defecto',
    'sysconfig.confirmReset': '¿Estás seguro de que deseas restablecer toda la configuración a los valores por defecto? Esta acción no se puede deshacer.',
    'sysconfig.saved': 'Configuración guardada correctamente',
    'sysconfig.resetSuccess': 'Configuración restablecida a valores por defecto',
    'sysconfig.addItem': 'Añadir elemento',
    'sysconfig.itemPlaceholder': 'Nuevo elemento',
    'sysconfig.expand': 'Expandir',
    'sysconfig.collapse': 'Colapsar',
    'sysconfig.softwarePlaceholder': 'Nueva tecnología',
    'sysconfig.criticality.critical': 'Crítica',
    'sysconfig.criticality.high': 'Alta',
    'sysconfig.criticality.medium': 'Media',
    'sysconfig.criticality.low': 'Baja',
  },
  en: {
    // Header
    'header.config': 'Configuration',
    'header.guide': 'Technical Guide',
    'header.about': 'About',
    'header.menu': 'Menu',
    'header.theme.light': 'Light',
    'header.theme.dark': 'Dark',
    
    // Home
    'home.footer': 'Click on any virtual machine to see more details',
    
    // Configuration
    'config.title': 'Technical Guide and Troubleshooting',
    'config.subtitle': 'Complete documentation for installation, configuration and troubleshooting',
    'config.toc': 'Table of Contents',
    'config.back': 'Back to diagram',
    'config.copy': 'Copy',
    'config.copied': 'Copied',
    
    // About
    'about.title': 'About the Architecture',
    'about.subtitle': 'Detailed information about the Proxmox system and its virtual machines',
    'about.overview.title': 'System Overview',
    'about.overview.intro': 'This system is built on',
    'about.overview.proxmox': 'Proxmox VE',
    'about.overview.description': 'an open-source hypervisor based on KVM that allows running multiple virtual machines on a single physical server.',
    'about.overview.features': 'The architecture is designed to separate roles and responsibilities, enabling:',
    'about.overview.storage': 'Centralized and shared storage (NFS)',
    'about.overview.production': 'Isolated and critical production services',
    'about.overview.gpu': 'GPU acceleration for specialized workloads',
    'about.overview.cicd': 'Development and CI/CD environment separated from production',
    'about.hardware.title': 'Physical Hardware Specifications',
    'about.hardware.cpu': 'CPU',
    'about.hardware.cpuValue': 'physical cores',
    'about.hardware.ram': 'RAM',
    'about.hardware.ramValue': 'GB of physical memory',
    'about.hardware.gpu': 'GPU',
    'about.hardware.gpuValue': 'NVIDIA GTX 1060 6GB (passthrough to VM103)',
    'about.hardware.storage': 'Storage',
    'about.hardware.storageValue': 'HDD array + SSD for system disks',
    'about.resources.title': 'Resource Allocation',
    'about.resources.description': 'The resource allocation strategy uses controlled overcommit:',
    'about.resources.cpu': 'CPU Overcommit',
    'about.resources.cpuDesc': 'Allocated',
    'about.resources.ram': 'RAM Overcommit',
    'about.resources.ramDesc': 'Allocated',
    'about.resources.on': 'on',
    'about.resources.physical': 'physical',
    'about.resources.ratio': 'ratio',
    'about.resources.overcommit': 'overcommit',
    'about.concepts.title': 'Key Concepts',
    'about.concepts.nfs': 'NFS (Network File System)',
    'about.concepts.nfsDesc': 'Protocol that allows sharing storage between machines. TrueNAS (VM101) acts as NFS server, providing shared storage to all other VMs.',
    'about.concepts.docker': 'Docker & Containers',
    'about.concepts.dockerDesc': 'Containerization technology that allows packaging applications with their dependencies. Used in VM102, VM103 and VM104 to run isolated services.',
    'about.concepts.jenkins': 'Jenkins CI/CD',
    'about.concepts.jenkinsDesc': 'Automation system that orchestrates build, test and deployment pipelines. Jenkins Master (VM102) coordinates with Jenkins Agent (VM104).',
    'about.concepts.passthrough': 'GPU Passthrough',
    'about.concepts.passthroughDesc': 'Technique that allows a VM to directly access a physical GPU device. Requires special configuration (q35 chipset, OVMF BIOS, IOMMU enabled).',
    'about.practices.title': 'Best Practices',
    'about.practices.monitor': 'Monitor memory usage with',
    'about.practices.monitorDesc': 'to detect memory pressure',
    'about.practices.backup': 'Perform regular backups of critical VMs (VM101, VM102, VM103)',
    'about.practices.snapshots': 'Use ZFS snapshots in TrueNAS for data protection',
    'about.practices.separate': 'Keep development (VM104) and production (VM102) environments separate',
    'about.explore.title': 'Explore the Architecture',
    'about.explore.description': 'Click on any virtual machine in the diagram to see specific details about its configuration, services, and troubleshooting guide.',
    'about.explore.button': 'Go to Interactive Diagram',
    'about.back': 'Back to diagram',
    
    // Configuration Guide
    'configGuide.resources.title': 'Resource Summary',
    'configGuide.resources.cpu': 'CPU',
    'configGuide.resources.ram': 'RAM',
    'configGuide.resources.physical': 'Physical',
    'configGuide.resources.assigned': 'Assigned',
    'configGuide.resources.ratio': 'Ratio',
    'configGuide.resources.cores': 'cores',
    'configGuide.resources.overcommit': 'Overcommit',
    'configGuide.vms.title': 'Virtual Machines',
    
    // Technical Guide - Sections
    'techGuide.physical.title': 'Physical Infrastructure',
    'techGuide.physical.description': 'Physical hardware specifications of the Proxmox server',
    'techGuide.physical.content': 'The Proxmox server has 4 physical cores, 32GB RAM, an NVIDIA GTX 1060 6GB GPU with passthrough, and HDD storage with SSD for system disks.',
    'techGuide.physical.cpuRam.title': 'CPU and RAM',
    'techGuide.physical.cpuRam.content': 'The server has 4 physical cores and 32GB of physical RAM.',
    'techGuide.physical.gpuStorage.title': 'GPU and Storage',
    'techGuide.physical.gpuStorage.content': 'NVIDIA GTX 1060 6GB available for passthrough to VM103. Storage with HDD array (passthrough to TrueNAS) and SSD for VM system disks.',
    'techGuide.physical.resourceAllocation.title': 'Resource Allocation Strategy',
    'techGuide.physical.resourceAllocation.content': 'Controlled overcommit is used: 8 vCPU assigned on 4 cores (2:1 ratio, normal in virtualization) and 38GB RAM assigned on 32GB physical (6GB overcommit, acceptable because TrueNAS and VM103 rarely use maximum).',
    
    'techGuide.vms.title': 'Virtual Machine Configuration',
    'techGuide.vms.description': 'Configuration details for each virtual machine',
    'techGuide.vms.content': 'Four main virtual machines: TrueNAS (storage), DockerHost (production), GPUProduction (GPU), and StagingAgent (development/CI/CD).',
    'techGuide.vms.vm101.title': 'VM101 - TrueNAS (Storage Server)',
    'techGuide.vms.vm101.content': 'NFS storage server providing exports for all VMs. Configuration: 2 Cores, 16GB RAM, UEFI BIOS, HDD Passthrough, QEMU Guest Agent enabled.',
    'techGuide.vms.vm102.title': 'VM102 - DockerHost (Production Server)',
    'techGuide.vms.vm102.content': 'Main production environment with Docker, Nginx Reverse Proxy and Jenkins Master. Criticality: HIGH - no downtime allowed.',
    'techGuide.vms.vm103.title': 'VM103 - GPUProduction (GPU Production Server)',
    'techGuide.vms.vm103.content': 'GPU-accelerated services for media and AI workloads. CRITICAL - no downtime allowed. Requires special GPU passthrough configuration.',
    'techGuide.vms.vm104.title': 'VM104 - StagingAgent (Development & CI/CD Agent)',
    'techGuide.vms.vm104.content': 'Jenkins agent and development/testing environment. Criticality: MEDIUM - can be restarted without affecting production.',
    
    'techGuide.installation.title': 'Installation and Configuration',
    'techGuide.installation.description': 'Step-by-step guides to install and configure each component',
    'techGuide.installation.content': 'Standard procedures to configure Ubuntu VMs, Docker, NFS, GPU and Jenkins.',
    'techGuide.installation.ubuntu.title': 'Standard Ubuntu VM Configuration',
    'techGuide.installation.ubuntu.content': 'Steps to configure a new Ubuntu VM with Docker, NFS and useful tools.',
    'techGuide.installation.gpu.title': 'GPU Configuration (VM103)',
    'techGuide.installation.gpu.content': 'Additional steps to configure GPU on VM103 after base setup.',
    'techGuide.installation.jenkinsMaster.title': 'Jenkins Master Configuration (VM102)',
    'techGuide.installation.jenkinsMaster.content': 'Installation of Jenkins Master as Docker container on VM102.',
    'techGuide.installation.jenkinsAgent.title': 'Jenkins Agent Configuration (VM104)',
    'techGuide.installation.jenkinsAgent.content': 'Configuration of VM104 as Jenkins agent.',
    
    'techGuide.backup.title': 'Backup Strategy',
    'techGuide.backup.description': 'Backup procedures for VMs and data',
    'techGuide.backup.content': 'Proxmox snapshots, Docker volume backups and ZFS snapshots on TrueNAS.',
    'techGuide.backup.proxmox.title': 'Proxmox VM Backups',
    'techGuide.backup.proxmox.content': 'Snapshots and backups of critical virtual machines.',
    'techGuide.backup.docker.title': 'Docker Volume Backups',
    'techGuide.backup.docker.content': 'Automated script for Docker volume backup.',
    'techGuide.backup.zfs.title': 'ZFS Snapshots (TrueNAS)',
    'techGuide.backup.zfs.content': 'Automatic snapshot configuration in TrueNAS.',
    
    'techGuide.monitoring.title': 'Monitoring and Maintenance',
    'techGuide.monitoring.description': 'Commands and procedures to monitor the system',
    'techGuide.monitoring.content': 'Tools and commands to monitor Proxmox, Docker, network and GPU.',
    'techGuide.monitoring.proxmox.title': 'Proxmox Host Monitoring',
    'techGuide.monitoring.proxmox.content': 'Commands to monitor hypervisor and VMs status.',
    'techGuide.monitoring.docker.title': 'Docker Monitoring',
    'techGuide.monitoring.docker.content': 'Commands to monitor containers and Docker resources.',
    'techGuide.monitoring.gpu.title': 'GPU Monitoring (VM103)',
    'techGuide.monitoring.gpu.content': 'Commands to monitor GPU status and usage.',
    'techGuide.monitoring.network.title': 'Network Diagnostics',
    'techGuide.monitoring.network.content': 'Commands to diagnose connectivity issues.',
    
    'techGuide.troubleshooting.title': 'Troubleshooting Guide',
    'techGuide.troubleshooting.description': 'Solutions for common problems',
    'techGuide.troubleshooting.content': 'Procedures to diagnose and resolve frequent system issues.',
    'techGuide.troubleshooting.vmWontStart.title': 'VM Won\'t Start',
    'techGuide.troubleshooting.vmWontStart.content': 'Steps to diagnose why a VM cannot start.',
    'techGuide.troubleshooting.nfsMountFails.title': 'NFS Mount Failure',
    'techGuide.troubleshooting.nfsMountFails.content': 'Diagnosis and solution of NFS problems.',
    'techGuide.troubleshooting.dockerWontStart.title': 'Docker Container Won\'t Start',
    'techGuide.troubleshooting.dockerWontStart.content': 'Diagnosis of Docker container problems.',
    'techGuide.troubleshooting.gpuPassthrough.title': 'GPU Passthrough Issues (VM103)',
    'techGuide.troubleshooting.gpuPassthrough.content': 'Diagnosis of GPU passthrough problems.',
    'techGuide.troubleshooting.jenkinsAgent.title': 'Jenkins Agent Connection Issues',
    'techGuide.troubleshooting.jenkinsAgent.content': 'Diagnosis of connection problems between Jenkins Master and Agent.',
    'techGuide.troubleshooting.outOfMemory.title': 'Out of Memory (RAM Overcommit)',
    'techGuide.troubleshooting.outOfMemory.content': 'Diagnosis and solution of memory pressure problems.',
    'techGuide.troubleshooting.diskSpace.title': 'Disk Space Issues',
    'techGuide.troubleshooting.diskSpace.content': 'Diagnosis and freeing disk space.',
    'techGuide.troubleshooting.networkConnectivity.title': 'Network Connectivity Issues',
    'techGuide.troubleshooting.networkConnectivity.content': 'Diagnosis of network problems.',
    'techGuide.troubleshooting.slowPerformance.title': 'Slow Performance',
    'techGuide.troubleshooting.slowPerformance.content': 'Diagnosis of performance problems.',
    'techGuide.troubleshooting.reverseProxy.title': 'Reverse Proxy Issues',
    'techGuide.troubleshooting.reverseProxy.content': 'Diagnosis of Nginx reverse proxy problems.',
    
    'techGuide.security.title': 'Security Considerations',
    'techGuide.security.description': 'Security configuration and hardening',
    'techGuide.security.content': 'Security best practices for Proxmox, Docker, Jenkins and SSH.',
    'techGuide.security.firewall.title': 'Firewall Configuration',
    'techGuide.security.firewall.content': 'Firewall rules for Proxmox and VMs.',
    'techGuide.security.jenkins.title': 'Jenkins Security',
    'techGuide.security.jenkins.content': 'Security best practices for Jenkins.',
    'techGuide.security.docker.title': 'Docker Security',
    'techGuide.security.docker.content': 'Security best practices for Docker.',
    'techGuide.security.ssh.title': 'SSH Hardening',
    'techGuide.security.ssh.content': 'Secure SSH configuration on all VMs.',
    
    // ArchitectureDiagram
    'diagram.clickDetails': 'Click for more details',
    'diagram.services': 'Services',
    'diagram.specialHardware': 'Special Hardware',
    'diagram.cpu': 'CPU',
    'diagram.ram': 'RAM',
    'diagram.gb': 'GB',
    'diagram.nfsSharedStorage': 'NFS Shared Storage',
    'diagram.proxmoxHypervisor': 'Proxmox VE Hypervisor',
    'diagram.internetAccess': 'Internet Access',
    'diagram.gpu': 'GPU',
    'diagram.passthroughToVm': 'Passthrough to VM',
    'diagram.storage': 'Storage',
    'diagram.passthroughToTruenas': 'Passthrough to TrueNAS',
    'diagram.externalClient': 'External Client\n(Internet)',
    'diagram.passthrough': 'Passthrough',
    'diagram.manages': 'Manages',
    'diagram.hddPassthrough': 'HDD Passthrough',
    'diagram.nfsServer': 'NFS Server',
    'diagram.nfsMount': 'NFS Mount',
    'diagram.gpuPassthrough': 'GPU Passthrough',
    'diagram.internet': 'Internet',
    'diagram.httpHttps': 'HTTP/HTTPS',
    'diagram.proxyTo': 'Proxy → Jellyfin/Ollama',
    'diagram.jenkinsMaster': 'Jenkins Master',
    'diagram.buildResults': 'Build Results',
    'diagram.data': 'Data',
    'diagram.media': 'Media',
    'diagram.workspace': 'Workspace',
    'diagram.hddSsd': 'HDD + SSD',
    'diagram.controls': 'Controls',
    'diagram.showAllServices': 'Show all services',
    'diagram.hideAllServices': 'Hide all services',
    'diagram.vmControl': 'VM Control',
    'diagram.showAll': 'Show All',
    'diagram.hideAll': 'Hide All',
    'diagram.saveCheckpoint': 'Save Checkpoint',
    'diagram.legend': 'Legend',
    'diagram.provides': 'Provides',
    'diagram.showServices': 'Show services',
    'diagram.hideServices': 'Hide services',
    'diagram.customConnection': 'Custom connection',
    'diagram.instructions': 'Instructions',
    'diagram.clickEdge': 'Click on a connection to select it',
    'diagram.pressDelete': 'Press Delete/Backspace to remove',
    'diagram.doubleClickEdit': 'Double-click on a connection to edit or delete it',
    'diagram.editLabel': 'Edit Connection Label',
    'diagram.labelText': 'Label text',
    'diagram.enterLabel': 'Enter new name...',
    'diagram.resetConnections': 'Reset Connections',
    'diagram.resetDiagram': 'Reset Diagram',
    'diagram.confirmReset': 'Are you sure you want to reset all connections to their default state? All custom connections and modified labels will be removed.',
    
    // VM Detail
    'vm.back': 'Back to diagram',
    'vm.notFound': 'Virtual Machine not found',
    'vm.notFoundDesc': 'does not exist in the architecture.',
    'vm.notFoundButton': 'Back to diagram',
    'vm.hardware': 'Hardware Configuration',
    'vm.hardware.cpu': 'CPU',
    'vm.hardware.cores': 'Cores',
    'vm.hardware.ram': 'RAM',
    'vm.hardware.disk': 'Disk',
    'vm.hardware.bios': 'BIOS',
    'vm.hardware.machine': 'Machine Type',
    'vm.hardware.special': 'Special Hardware',
    'vm.services': 'Services',
    'vm.servicesDesc': 'Available applications for use',
    'vm.software': 'Software & Technologies',
    'vm.softwareDesc': 'Technology stack and system tools',
    'vm.editConfig': 'Edit Configuration',
    'vm.addService': 'Add Application',
    'vm.addSoftware': 'Add Technology',
    'vm.newServicePlaceholder': 'Application name',
    'vm.newSoftwarePlaceholder': 'Technology name',
    'vm.nfs': 'NFS Mounts',
    'vm.ports': 'Ports',
    'vm.portsExposed': 'Exposed Ports',
    'vm.portsInternal': 'Internal Ports',
    'vm.design': 'Design Decision Rationale',
    'vm.troubleshooting': 'Troubleshooting Guide',
    
    // NotFound
    'notFound.title': 'Page Not Found',
    'notFound.description': 'Sorry, the page you are looking for does not exist.',
    'notFound.description2': 'It may have been moved or deleted.',
    'notFound.button': 'Go Home',
    
    // ErrorBoundary
    'error.title': 'An unexpected error occurred.',
    'error.reload': 'Reload Page',
    
    // Footer
    'footer.text': 'Architecture Dashboard',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.usernamePlaceholder': 'Enter your username',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.loggingIn': 'Logging in...',
    'auth.loginSuccess': 'Login successful',
    'auth.loginError': 'Invalid username or password',
    'auth.loginRequired': 'You must be logged in to perform this action',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.reset': 'Reset',
    'common.confirm': 'Confirm',
    
    // System Configuration
    'sysconfig.title': 'System Configuration',
    'sysconfig.subtitle': 'Configure your Proxmox infrastructure and virtual machines',
    'sysconfig.proxmox': 'Proxmox Server',
    'sysconfig.proxmox.name': 'Name',
    'sysconfig.proxmox.cpu': 'CPU (Cores)',
    'sysconfig.proxmox.ram': 'RAM (GB)',
    'sysconfig.proxmox.gpu': 'GPU',
    'sysconfig.proxmox.storage': 'Storage',
    'sysconfig.vms': 'Virtual Machines',
    'sysconfig.vm.add': 'Add VM',
    'sysconfig.vm.name': 'Name',
    'sysconfig.vm.id': 'VM ID',
    'sysconfig.vm.role': 'Role',
    'sysconfig.vm.description': 'Description',
    'sysconfig.vm.criticality': 'Criticality',
    'sysconfig.vm.cpu': 'CPU (Cores)',
    'sysconfig.vm.ram': 'RAM (GB)',
    'sysconfig.vm.disk': 'Disk (GB)',
    'sysconfig.vm.diskType': 'Disk Type',
    'sysconfig.vm.bios': 'BIOS',
    'sysconfig.vm.machineType': 'Machine Type',
    'sysconfig.vm.color': 'Color',
    'sysconfig.vm.services': 'Services',
    'sysconfig.vm.software': 'Software & Technologies',
    'sysconfig.vm.specialHardware': 'Special Hardware',
    'sysconfig.vm.nfsMounts': 'NFS Mounts',
    'sysconfig.vm.ports': 'Ports',
    'sysconfig.vm.portsExposed': 'Exposed Ports',
    'sysconfig.vm.portsInternal': 'Internal Ports',
    'sysconfig.portPlaceholder': 'E.g: 80 (HTTP)',
    'sysconfig.vm.remove': 'Remove VM',
    'sysconfig.services.title': 'Global Services',
    'sysconfig.services.add': 'Add Service',
    'sysconfig.services.name': 'Name',
    'sysconfig.services.imageUrl': 'Image URL',
    'sysconfig.services.remove': 'Remove',
    'sysconfig.services.confirmRemove': 'Are you sure you want to remove this service? It will be removed from all VMs that use it.',
    'sysconfig.vm.confirmRemove': 'Are you sure you want to remove this VM?',
    'sysconfig.save': 'Save Configuration',
    'sysconfig.reset': 'Reset to Defaults',
    'sysconfig.confirmReset': 'Are you sure you want to reset all configuration to defaults? This action cannot be undone.',
    'sysconfig.saved': 'Configuration saved successfully',
    'sysconfig.resetSuccess': 'Configuration reset to defaults',
    'sysconfig.addItem': 'Add item',
    'sysconfig.itemPlaceholder': 'New item',
    'sysconfig.expand': 'Expand',
    'sysconfig.collapse': 'Collapse',
    'sysconfig.softwarePlaceholder': 'New technology',
    'sysconfig.criticality.critical': 'Critical',
    'sysconfig.criticality.high': 'High',
    'sysconfig.criticality.medium': 'Medium',
    'sysconfig.criticality.low': 'Low',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'es' ? 'en' : 'es'));
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

